apiVersion: v1
kind: Config
preferences:
  colors: true
current-context: first-cluster
contexts:
  - context:
      cluster: ${first_cluster_name}
      namespace: default
      user: ${first_user_name}
    name: first-cluster
  - context:
      cluster: ${second_cluster_name}
      namespace: default
      user: ${second_user_name}
    name: second-cluster
clusters:
  - cluster:
      server: https://${first_endpoint}
      certificate-authority-data: ${first_cluster_ca}
    name: ${first_cluster_name}
  - cluster:
      server: https://${second_endpoint}
      certificate-authority-data: ${second_cluster_ca}
    name: ${second_cluster_name}
users:
  - name: ${first_user_name}
    user:
      password: ${first_user_password}
      username: ${first_user_name}
      client-certificate-data: ${first_client_cert}
      client-key-data: ${first_client_cert_key}
  - name: ${second_user_name}
    user:
      password: ${second_user_password}
      username: ${second_user_name}
      client-certificate-data: ${second_client_cert}
      client-key-data: ${second_client_cert_key}
